openapi: 3.1.0
info:
  title: Magma Gestion API
  description: API de gestion des métadonnées statistiques
  contact:
    name: dr59-sndil
    url: https://www.insee.fr/fr/accueil
    email: dr59-sinl-equipe-maintenance-rmes@insee.fr
  version: 1.4.11
tags:
  - name: Series-Operations
    description: Consultation des Séries et Opérations de la base de gestion
  - name: Datasets
    description: Consultation Magma API - datasets
servers:
  - url: http://localhost:8080

security:
  - bearerAuth: []

paths:

  # ============================================
  # SERIES / OPERATIONS
  # ============================================
  /operations/series:
    get:
      tags:
        - Series-Operations
      summary: Get all series
      operationId: getAllSeries
      parameters:
        - name: dateMiseAJour
          in: query
          description: 'Date of last update. Example: 2023-01-31'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SerieById'
        '404':
          description: Not found
        '500':
          description: Internal server error

  /operations/serie/{id}:
    get:
      tags:
        - Series-Operations
      summary: Get one serie
      operationId: getSerieById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SerieById'
        '404':
          description: Not found
        '500':
          description: Internal server error

  /operations/operation/{id}:
    get:
      tags:
        - Series-Operations
      summary: Get operation by code
      operationId: getOperationByCode
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationById'
        '404':
          description: Not found
        '500':
          description: Internal server error

  /operations/indicateur/{id}:
    get:
      tags:
        - Series-Operations
      summary: Get one indicator
      operationId: getIndicatorById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Indicateur'
        '404':
          description: Not found
        '500':
          description: Internal server error


  # ============================================
  # DATASETS
  # ============================================

  /dataset/{id}:
    get:
      tags:
        - Datasets
      summary: Get one dataset
      operationId: getDataSetById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/Dataset200'
        '400':
          $ref: '#/components/responses/IncorrectRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '500':
          $ref: '#/components/responses/ServerError'
    patch:
      tags:
        - Datasets
      summary: Update some properties of a dataset
      description: Update ObservationNumber, issued, modified, temporal, or numSeries of a dataset
      operationId: patchDataSet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: JSON with parameters you want to change
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchDataset'
            example:
              issued: "2022-11-11"
              modified: "2023-12-31"
              temporal:
                startPeriod: "2020-01-01"
                endPeriod: "2024-01-01"
              numObservations: 150
              numSeries: 12
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/IncorrectRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '500':
          $ref: '#/components/responses/ServerError'

  /dataset/{id}/distributions:
    get:
      tags:
        - Datasets
      summary: Get dataset distributions
      operationId: getDataSetDistributionsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/DistributionsListe200'
        '400':
          $ref: '#/components/responses/IncorrectRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '500':
          $ref: '#/components/responses/ServerError'


  /datasets/list:
    get:
      tags:
        - Datasets
      summary: Get list of datasets
      operationId: getListDatasets
      parameters:
        - name: dateMiseAJour
          in: query
          description: 'Date of last update. Example: 2023-01-31'
          required: false
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/DatasetsListe200'
        '400':
          $ref: '#/components/responses/IncorrectRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:

    IncorrectRequest:
      description: 'La syntaxe de la requête est incorrecte'

    NotFound:
      description: 'Ressource non trouvée'

    NotAcceptable:
      description: 'L''en-tête HTTP ''Accept'' contient une valeur non acceptée'

    ServerError:
      description: 'Erreur interne du serveur'

    Dataset200:
      description: 'Opération réussie'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Dataset'
          examples:
            défaut:
              $ref: '#/components/examples/Dataset'
        application/xml:
          schema:
            $ref: '#/components/schemas/Dataset'
          examples:
            défaut:
              $ref: '#/components/examples/Dataset'

    DistributionsListe200:
      description: 'Opération réussie'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListeDistributions'
          examples:
            défaut:
              $ref: '#/components/examples/ListeDistributions'
        application/xml:
          schema:
            $ref: '#/components/schemas/ListeDistributions'
          examples:
            défaut:
              $ref: '#/components/examples/ListeDistributions'

    DatasetsListe200:
      description: 'Opération réussie pour les datasets'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListeDatasets'
          examples:
            défaut:
              $ref: '#/components/examples/ListeDatasets'
        application/xml:
          schema:
            $ref: '#/components/schemas/ListeDatasets'
          examples:
            défaut:
              $ref: '#/components/examples/ListeDatasets'

  schemas:
    # ============================================
    # COMMON / SHARED SCHEMAS
    # ============================================

    IdLabel:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        label:
          type: array
          items:
            $ref: './langue-contenu.schema.json'


    # ============================================
    # SERIES / OPERATIONS SCHEMAS
    # ============================================
    SerieById:
      type: object
      properties:
        seriesId:
          type: string
        uri:
          type: string
        label:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        altLabel:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        resume:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        noteHistorique:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        type:
          $ref: 'id-uri-label.schema.json'
        frequenceCollecte:
          $ref: 'id-uri-label.schema.json'
        rapportQualite:
          $ref: '#/components/schemas/RapportQualite'
        famille:
          $ref: 'id-uri-label.schema.json'
        seriesPrecedentes:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        seriesSuivantes:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        seriesLiees:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        operations:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        indicateurs:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        dateCreation:
          type: string
          format: date
        dateMiseAJour:
          type: string
          format: date
        proprietaires:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        organismesResponsables:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        partenaires:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        servicesCollecteurs:
          type: array
          items:
            $ref: 'id-uri-label.schema.json'
        statutValidation:
          type: string
        series:
          type: string
        frequence:
          $ref: 'id-uri-label.schema.json'
        nbOperation:
          type: string

    RapportQualite:
      type: object
      properties:
        id:
          type: string
        uri:
          type: string

    Frequence:
      type: object
      properties:
        id:
          type: string
        label:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        uri:
          type: string


    SerieRef:
      type: object
      properties:
        id:
          type: string
        label:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        uri:
          type: string
        frequence:
          $ref: '#/components/schemas/Frequence'

    OperationById:
      type: object
      properties:
        id:
          type: string
        uri:
          type: string
        label:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        altLabel:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        millesime:
          type: string
        serie:
          $ref: '#/components/schemas/SerieRef'
        rapportQualite:
          $ref: '#/components/schemas/RapportQualite'
        dateCreation:
          type: string
          format: date
        dateMiseAJour:
          type: string
          format: date
        statutValidation:
          type: string

    Indicateur:
      type: object
      properties:
        id:
          type: string
        uri:
          type: string
        label:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        altLabel:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        resume:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        noteHistorique:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        frequenceCollecte:
          $ref: './id-uri-label.schema.json'
        rapportQualite:
          $ref: '#/components/schemas/RapportQualite'
        seriesContributrices:
          type: array
          items:
            $ref: './id-uri-label.schema.json'
        seriesLiees:
          type: array
          items:
            $ref: './id-uri-label.schema.json'
        indicateursLies:
          type: array
          items:
            $ref: './id-uri-label.schema.json'
        dateCreation:
          type: string
        dateMiseAJour:
          type: string
        proprietaires:
          type: array
          items:
            $ref: './id-uri-label.schema.json'
        organismesResponsables:
          type: array
          items:
            $ref: './id-uri-label.schema.json'
        partenaires:
          type: array
          items:
            $ref: './id-uri-label.schema.json'
        statuValidation:
          type: string

    # ============================================
    # DATASETS SCHEMAS
    # ============================================

    Theme:
      type: object
      properties:
        uri:
          type: string
        label:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        themeTaxonomy:
          type: string

    LandingPage:
      type: object
      properties:
        lang:
          type: string
        url:
          type: string

    ProcessStep:
      type: object
      properties:
        id:
          type: string
        label:
          $ref: 'langue-contenu.schema.json'

    Temporal:
      type: object
      properties:
        startPeriod:
          type: string
        endPeriod:
          type: string

    Structure:
      type: object
      properties:
        uri:
          type: string
        id:
          type: string
        dsd:
          type: string

    WasDerivedFrom:
      type: object
      properties:
        datasets:
          type: array
          items:
            type: string
        description:
          type: array
          items:
            $ref: './langue-contenu.schema.json'


    ListeDistributions:
      description: 'Liste des distributions'
      type: array
      xml:
        wrapped: true
        name: Definition
      items:
        $ref: '#/components/schemas/Distribution'

    Distribution:
      type: object
      properties:
        identifier:
          type: string
        byteSize:
          type: string
        created:
          type: string
        description:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        downloadURL:
          type: array
          items:
            type: string
        format:
          type: string
        modified:
          type: string
        title:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        uri:
          type: string

    PatchDataset:
      type: object
      description: DTO for patching dataset properties
      properties:
        issued:
          type: string
          description: Issue date (format YYYY-MM-DD)
          example: "2022-11-11"
        modified:
          type: string
          description: Last modification date (format YYYY-MM-DD)
          example: "2023-12-31"
        temporal:
          $ref: '#/components/schemas/Temporal'
        numObservations:
          type: integer
          format: int32
          description: Number of observations
          example: 150
        numSeries:
          type: integer
          format: int32
          description: Number of series
          example: 12

    Dataset:
      type: object
      properties:
        id:
          type: string
        uri:
          type: string
        catalogRecordCreated:
          type: string
        catalogRecordModified:
          type: string
        catalogRecordCreator:
          type: string
        catalogRecordContributor:
          type: string
        identifier:
          type: string
        issued:
          type: string
        modified:
          type: string
        disseminationStatus:
          type: string
        validationState:
          type: string
        version:
          type: string
        creator:
          type: array
          items:
            $ref: '#/components/schemas/IdLabel'
        publisher:
          $ref: '#/components/schemas/IdLabel'
        title:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        subtitle:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        abstract:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        description:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        scopeNote:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        wasGeneratedBy:
          type: array
          items:
            $ref: '#/components/schemas/IdLabel'
        type:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        archiveUnit:
          type: array
          items:
            $ref: '#/components/schemas/IdLabel'
        accessRights:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        confidentialityStatus:
          type: array
          items:
            $ref: './langue-contenu.schema.json'
        theme:
          type: array
          items:
            $ref: '#/components/schemas/Theme'
        landingPage:
          type: array
          items:
            $ref: '#/components/schemas/LandingPage'
        processStep:
          $ref: '#/components/schemas/ProcessStep'
        accrualPeriodicity:
          $ref: 'langue-contenu.schema.json'
        temporal:
          $ref: '#/components/schemas/Temporal'
        temporalResolution:
          type: array
          items:
            $ref: 'langue-contenu.schema.json'
        spatial:
          $ref: '#/components/schemas/IdLabel'
        spatialResolution:
          type: array
          items:
            $ref: '#/components/schemas/IdLabel'
        spatialTemporal:
          type: string
        statisticalUnit:
          type: array
          items:
            $ref: '#/components/schemas/IdLabel'
        structure:
          $ref: '#/components/schemas/Structure'
        numObservations:
          type: integer
          format: int32
        numSeries:
          type: integer
          format: int32
        wasDerivedFrom:
          $ref: '#/components/schemas/WasDerivedFrom'
        relations:
          type: array
          items:
            type: string
        keyword:
          type: array
          items:
            $ref: './langue-contenu.schema.json'

    ListeDatasets:
      description: 'Liste des datasets'
      type: array
      xml:
        wrapped: true
        name: Definition
      items:
        $ref: '#/components/schemas/Dataset'

  examples:
    Dataset:
      value:
        code: '25baaf1f-61cf-4d50-9124-1477afca2aa4'
        uri: 'http://bauhaus/catalogues/jeuDeDonnees/25baaf1f-61cf-4d50-9124-1477afca2aa4'
        catalogRecordCreated: '2024-12-09T12:00:00.000'
        catalogRecordModified: '2024-12-09T12:00:00.000'
        catalogRecordCreator: 'http://bauhaus/organisations/insee/HIE2004937'
        identifier: 'DD_EEC_SERIES'
        validationState: 'Provisoire, jamais publiée'
        title:
          - contenu: 'Activité, emploi et chômage - séries longues'
            langue: 'fr'
          - contenu : 'Activité, emploi et chômage - séries longues'
            langue: 'en'
        description:
          - contenu: 'Les données sont détaillées par sexe, âge, diplôme et catégorie socio-professionnelle (PCS). Pour l’emploi, les données sont détaillées par type de contrat, composante du sous-emploi, temps de travail (temps complet ou partiel). Plusieurs indicateurs en taux sont disponibles : taux d''activité, taux d''emploi ou taux de chômage.\n\nCe jeu de données regroupe notamment les données annuelles de forte valeur (High Value Dataset ou HVD statistiques) désignées par Eurostat sur les sujets suivants : l''emploi , le chômage et la main d’œuvre potentielle.'
            langue: 'fr'
          - langue: 'en'
        scopeNote:
          - contenu: 'Des corrections sur les données concernant la population totale ainsi que sur l''emploi et la part dans l''emploi selon le plus haut diplôme obtenu, par sexe et âge regroupé, en moyenne annuelle ont été apportées en septembre 2024 afin de rectifier une erreur, portant sur les années 2018, 2019 et 2020 uniquement.'
            langue: 'fr'
          - langue: 'en'
        wasGeneratedBy:
          - contenu: 'http://bauhaus/operations/serie/s1223'
            langue: 'fr'
          - langue: 'en'

    ListeDistributions:
      value:
        - identifier: '6d0d296b-9ec5-42fa-a3d5-62ffe7c74dea'
          created: '2025-02-17T08:13:23.382171614'
          description:
            - contenu: 'fichier csv généré par l''API melodi'
              langue: 'fr'
            - langue: 'en'
          downloadURL:
          modified: '2025-02-17T08:13:23.382171614'
          title:
            - contenu: 'Capacités d''hébergements touristiques'
              langue: 'fr'
            - contenu: 'Tourism capacities'
              langue: 'en'
          uri: 'http://bauhaus/catalogues/distribution/6d0d296b-9ec5-42fa-a3d5-62ffe7c74dea'


    ListeDatasets:
      value:
        - id: '25baaf1f-61cf-4d50-9124-1477afca2aa4'
          uri: 'http://bauhaus/catalogues/jeuDeDonnees/25baaf1f-61cf-4d50-9124-1477afca2aa4'
          catalogRecordCreated: '2024-12-09T12:00:00.000'
          catalogRecordModified: '2024-12-09T12:00:00.000'
          catalogRecordCreator: 'http://bauhaus/organisations/insee/HIE2004937'
          validationState: 'Provisoire, jamais publiée'
          title:
            - contenu: 'Activité, emploi et chômage - séries longues'
              langue: 'fr'
            - contenu: 'Activité, emploi et chômage - séries longues'
              langue: 'en'
        - id: 'a85dab6c-ef0f-4caa-9763-c7f8c840e216'
          uri: 'http://bauhaus/catalogues/jeuDeDonnees/a85dab6c-ef0f-4caa-9763-c7f8c840e216'
          catalogRecordCreated: '2024-12-09'
          catalogRecordModified: '2024-12-09'
          validationState: 'Unpublished'
          title:
            - contenu: 'Activité des branches de l''économie'
              langue: 'fr'
            - contenu: 'Activité des branches de l''économie'
              langue: 'en'


